title = "Custom GitLeaks Configuration"

description = "Custom rules for detecting sensitive information in the repository."

[[rules]]
id = "api-key"
regex = "(?i)(api[_-]?key|secret[_-]?key|access[_-]?key)[\s:=\"']+[a-zA-Z0-9-_]{16,}"  # Regex to detect API keys
entropy = 3.5  # Minimum entropy to reduce false positives
path = "*"  # Apply to all files

tags = ["key", "api", "secret"]
